import type { Metadata } from 'next';
import { Manrope, Dancing_Script } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/navbar';
import { Footer } from '@/components/footer';
const manrope = Manrope({
	variable: '--font-manrope',
	subsets: ['latin'],
});

const dancingScript = Dancing_Script({
	variable: '--font-dancing-script',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${manrope.className} ${dancingScript.variable} antialiased`}
			>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
